### ISSUE TITLE
Background Image appending a semi colon? 

### ISSUE THREAD

**Issue by jenaro94** [kuldeepkeshwar/filbert-js#68]
Hi there, so me again, apparently when importing an image in react and using the base64 iamge as background, at the end there is a `:` being added that breaks the image.

https://cad-overlay.netlify.app/ 

Here's the app, right under the div root, you should have a div with the background image that is not being set properly, if you want to check out my repo: 

https://github.com/jenaro94/cad-overlay

If you inspect the css and remove that `:` the background image will show correctly.

**Comment by kuldeepkeshwar** [comment]
@jenaro94 thanks for report this.
This happened as `@filbert-js/css-ast` was tokenising css ruleset based on `;` & ':' only.

**Comment by jenaro94** [comment]
Should updating the library fix this?

**Comment by kuldeepkeshwar** [comment]
fixed in [@filbert-js/css-parser 0.0.7](https://github.com/kuldeepkeshwar/filbert-js/releases/tag/%40filbert-js%2Fcss-parser%400.0.7)
