### ISSUE TITLE
Add dark/light mode to website

### ISSUE THREAD

**Issue by kuldeepkeshwar** [kuldeepkeshwar/filbert-js#90]

**Comment by vivek32ta** [comment]
Hi Kuldeep,

I'd love to take this up...

Best,
Vivek

**Comment by kuldeepkeshwar** [comment]
@vivek32ta feel free to take it

**Comment by vivek32ta** [comment]
Hey I'm new to this haha... I'm getting this when I ran ```gatsby develop``` Any suggestions how to get around it?

![Untitled](https://user-images.githubusercontent.com/32357540/93182720-a7580380-f757-11ea-9610-8a7f478902f0.png)

**Comment by kuldeepkeshwar** [comment]
working fine on my side @vivek32ta ,  try deleting `.cache` folder

**Comment by vivek32ta** [comment]
I did. It's still the same thing.... I did ```gatsby clean``` too. And also, the process is to install all packages and run ```gatsby develop``` right?

**Comment by kuldeepkeshwar** [comment]
@vivek32ta Can you list the steps of commands(and current folder) you are using ?

Btw you can join the [help channel](https://discord.gg/cNZacw3) on discord

**Comment by kuldeepkeshwar** [comment]
fixed in #101
